title: Henrique Ferrari 
email: send_me_spam@gmail.com
description: A collection of projects and ideas I feel are worth sharing
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hferrari.github.io" 
twitter_username: no_tweeter
github_username: hferrri 

theme: minima
plugins:
  - jekyll-feed
