title: A journal for (hopefully) fun projects 
author: Henrique Ferrari
email: h86267145@gmail.com
description: Projects and ideas I feel are worth sharing
url: "https://hferrari.github.io" 
github_username: hferrari 

theme: minima
plugins:
  - jekyll-feed
